In [1]:
import numpy as np

In [2]:
theta = 0.0448

In [3]:
rot = np.matrix([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])

In [4]:
rot

matrix([[ 0.99899665, -0.04478502],
        [ 0.04478502,  0.99899665]])

In [5]:
cam_coords = (0.6278) * rot * (np.matrix([570.1, 0.1]).T)

In [6]:
cam_coords

matrix([[357.54685985],
        [ 16.09166731]])

In [7]:
cam_first_offset = (0.6278) * rot * (np.matrix([1500, 0]).T)

In [8]:
cam_first_offset

matrix([[940.75514326],
        [ 42.1740492 ]])

In [9]:
0.6278 * 1500

941.7

In [14]:
from stitcher.linear_stitcher import LinearStitcher
from imager.imaging_grid import ImagingGrid

In [36]:
grid = ImagingGrid()
grid.set_distance_between_images(1500)
grid.set_imaging_width(2000)
grid.set_imaging_height(2000)
grid.set_pixels_per_um(0.6265)
grid.set_top_left((0, 0))

In [37]:
stitcher = LinearStitcher(r"C:\Users\Luke\Desktop\chip-imager\chip-imaging\backend\prototyping\sample_data\test_manual_shift", grid)

In [61]:
theta = 0.053
rot = np.matrix([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])
cam_first_offset = (0.6265) * rot * (np.matrix([1500, 0]).T)

In [66]:
projected_x = 0.6265 * 1500

In [62]:
cam_first_offset

matrix([[938.43043006],
        [ 49.78343541]])

In [67]:
stitcher.set_xy_shift(projected_x - cam_first_offset[0], cam_first_offset[1])

In [68]:
stitcher.run()

[1881, 1978]
[941, 1928]
[2, 1879]
[1880, 1038]
[940, 988]
[1, 939]
[1879, 99]
[939, 49]
[0, 0]


## test a big stitch, determine theta

In [94]:
big_data = r"C:\Users\Luke\Desktop\chip-imager\chip-imaging\backend\prototyping\sample_data\test3"
grid = ImagingGrid()
grid.set_properties([0, 0], 20000, 10000, 1800, 0.62)
grid.set_imaging_width(20000)
grid.set_imaging_height(10000)
grid.set_pixels_per_um(0.625)

In [95]:
stitcher = LinearStitcher(big_data, grid)

In [102]:
dist = 1800
theta = -0.014
rot = np.matrix([[np.cos(theta), -np.sin(theta)], [np.sin(theta), np.cos(theta)]])
cam_first_offset = (0.6265) * rot * (np.matrix([dist, 0]).T)
projected_x = 0.6265 * dist

In [103]:

stitcher.set_xy_shift(projected_x - cam_first_offset[0], cam_first_offset[1])

In [104]:
stitcher.run()

[13501, 6560]
[12376, 6576]
[11251, 6592]
[10126, 6607]
[9001, 6623]
[7876, 6639]
[6751, 6655]
[5626, 6671]
[4501, 6686]
[3376, 6702]
[2251, 6718]
[1126, 6734]
[1, 6750]
[13501, 5435]
[12376, 5451]
[11251, 5467]
[10126, 5482]
[9001, 5498]
[7876, 5514]
[6751, 5530]
[5626, 5546]
[4500, 5561]
[3375, 5577]
[2250, 5593]
[1125, 5609]
[0, 5625]
[13500, 4310]
[12375, 4326]
[11250, 4342]
[10125, 4357]
[9000, 4373]
[7875, 4389]
[6750, 4405]
[5625, 4421]
[4500, 4436]
[3375, 4452]
[2250, 4468]
[1125, 4484]
[0, 4500]
[13500, 3185]
[12375, 3201]
[11250, 3217]
[10125, 3232]
[9000, 3248]
[7875, 3264]
[6750, 3280]
[5625, 3296]
[4500, 3311]
[3375, 3327]
[2250, 3343]
[1125, 3359]
[0, 3375]
[13500, 2060]
[12375, 2076]
[11250, 2092]
[10125, 2107]
[9000, 2123]
[7875, 2139]
[6750, 2155]
[5625, 2171]
[4500, 2186]
[3375, 2202]
[2250, 2218]
[1125, 2234]
[0, 2250]
[13500, 935]
[12375, 951]
[11250, 967]
[10125, 982]
[9000, 998]
[7875, 1014]
[6750, 1030]
[5625, 1046]
[4500, 1061]
[3375, 1077]
[2250, 1093]
[1125, 1